### ISSUE TITLE
Error: PageSize configuation is wrong: configured with 4096, but got 65536

### ISSUE THREAD

**Issue by travisboss** [TheRemote/Legendary-Bedrock-Container#10]
Getting this error when starting this container with the docker compose example.

I am using a Oracle Free Tier with four Arm cores, if there is more info you need please let me know.  I am trying to import a bedrock instance I had on a on prem server to this cloud server, I transferred my entire world over.

**Comment by travisboss** [comment]
To add the container does work, but this is the last thing I see.

**Comment by TheRemote** [comment]
Best I can tell this means that your Linux distro doesn't match Ubuntu's page file size for QEMU:  https://github.com/fluent/fluent-bit/issues/4270

It sounds like to me all this means is that your Linux distro isn't using the same page file size as the Docker container.  Someone in that thread even brought up the Oracle VM so I'm guessing this is a thing.

Does it cause any problems?  When you say this is the last thing you see do you mean that when you shut down the server that's the last line it shows?  Or does the server not actually work?

**Comment by travisboss** [comment]
It seems the server actually is running, but I am not getting any logs when I do `sudo docker logs mc` all I see is that error.

**Comment by TheRemote** [comment]
I'm guessing Oracle can't handle Box64 and needs to use the slower QEMU for emulation.

Can you try using -e UseQEMU=Y in your launch line?

**Comment by travisboss** [comment]
> I'm guessing Oracle can't handle Box64 and needs to use the slower QEMU for emulation.
> 
> Can you try using -e UseQEMU=Y in your launch line?
> 
> I would probably recommend using the Geyser container even if you want to play using Bedrock but I understand you're using an existing server so that is a bit of a dealbreaker for switching to a server that doesn't require emulation on ARM!
> 
> ARM is the absolute worst choice to run this on and it's actually cheating under the hood to do it at all (this is why very few projects support running Bedrock on ARM). It uses emulation but it sounds like Oracle isn't configured correctly for Box64 (and will likely have to fall back using QEMU).

Sorry for the late reply, but I did try QEMU initially, it did start per logs but my users could not log in, the server is still working so I am sort of just treading water right now until I think of another solution, but will look at geyser container.

**Comment by TheRemote** [comment]
Hey travisboss,

Welcome back, don't sweat it at all!  I thought I might have closed this one but maybe it was another one since I didn't think we were going to hear from you again but I'm glad you came back.

So this is actually sounding really good.  QEMU is working properly.  Now you are running into the normal Oracle stuff which is people can't connect.  This is well-known for sure with Oracle and I can definitely help with this.  You definitely fixed the major problem with Box64 and page size by switching to QEMU.

The Oracle configuration stuff looks like this:

```
Troubleshooting Note - Oracle Virtual Machines
A very common problem people have with the Oracle Virtual Machine tutorials out there that typically show you how to use a free VM is that the VM is much more difficult to configure than just about any other product / offering out there.
The symptom you will have is that nobody will be able to connect.
It is because there are several steps you need to take to open the ports on the Oracle VM. You need to both:

    Set the ingress ports (TCP/UDP) in the Virtual Cloud Network (VCN) security list
    *and* set the ingress ports in a Network Security Group assigned to your instance


Both of these settings are typically required before you will be able to connect to your VM instance. This is purely configuration related and has nothing to do with the script or the Minecraft server itself.

I do not recommend this platform due to the configuration difficulty but the people who have gone through the pain of configuring an Oracle VM have had good experiences with it after that point. Just keep in mind it's going to be a rough ride through the configuration for most people.

Here are some additional links:

    https://jamesachambers.com/official-minecraft-bedrock-dedicated-server-on-raspberry-pi/comment-page-8/#comment-13946
    https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/comment-page-53/#comment-13936
    https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/comment-page-49/#comment-13377
    https://jamesachambers.com/legendary-minecraft-bedrock-container/comment-page-2/#comment-13706

```

I'm positive you'll be able to get it going now that we got the strange page size configuration error cleared up here!
