### ISSUE TITLE
Unable to connect to update website

### ISSUE THREAD

**Issue by paquito800** [TheRemote/Legendary-Bedrock-Container#13]
Hi, im trying to run this on my raspberry pi but it gets stuck at "Unable to connect to update website (internet connection may be down).  Skipping update ...
Starting Minecraft server..." and then it resets  and do the same on an infinite loop, I got no clue of how to fix this.

**Comment by paquito800** [comment]
Ive tried to fix the DNS on docker for a whole day witthout results, is there any way to me add on the server the current minecraft version manually?

**Comment by TheRemote** [comment]
To fix this the Raspberry Pi needs to be updated to the latest version of Raspberry Pi OS.

sudo apt upgrade will not do this.  You need to reinstall the latest version downloaded from the Raspberry Pi web site.

Hopefully that helps!
