### ISSUE TITLE
Pi5: Error: PageSize configuration is wrong: configured with 4096, but got 16384

### ISSUE THREAD

**Issue by Faeldra** [TheRemote/Legendary-Bedrock-Container#14]
Hi!

I have used your Docker for years on the Pi4 and im loving it.
Its not working on my Pi5 8GB. 

Here is some information that might be usefull.
Hope you can fix it so i can use your awsome build!

docker run -it -v /data/lib/minecraft:/minecraft -p 19132:19132/udp -p 19132:19132 -p 19133:19133/udp -p 19133:19133 05jchambers/legendary-bedrock-container:latest

Minecraft Bedrock Server Docker script by James A. Chambers
Latest version always at https://github.com/TheRemote/Legendary-Bedrock-Container
Don't forget to set up port forwarding on your router!  The default port is 19132
Ports used - IPV4: 19132 - IPV6: 19133
Taking ownership of all server files/folders in /minecraft...
Complete
Checking for the latest version of Minecraft Bedrock server ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  340k    0  340k    0     0   545k      0 --:--:-- --:--:-- --:--:--  545k
Latest version online is bedrock-server-1.20.62.02.zip
Current install is: bedrock-server-1.20.62.02.zip
Latest version bedrock-server-1.20.62.02.zip is already installed
Starting Minecraft server...
[2024-02-22 00:54:58] Error: PageSize configuration is wrong: configured with 4096, but got 16384

xxxxxx@vissiepi5:~ $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by TheRemote** [comment]
This is now fixed for the Pi 5 and available!
