### ISSUE TITLE
Server version download: version.html: No such file or directory

### ISSUE THREAD

**Issue by jcm-shove-it** [TheRemote/Legendary-Bedrock-Container#17]
Hi, server version file is not available anymore.

> $ curl --no-progress-meter -H "Accept-Encoding: identity" -H "Accept-Language: en" -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.$RandNum.212 Safari/537.36" -o /minecraft/downloads/version.html https://www.minecraft.net/en-us/download/server/bedrock
Warning: Failed to open the file /minecraft/downloads/version.html: No such 
Warning: file or directory
curl: (23) Failure writing output to destination

My bedrock version is now behind:
> Version: 1.21.30.03
While on minecraft.net (non-preview) version is 1.21.31.04

BR, Joerg

**Comment by GluteCramp** [comment]
I get the following error on loop in the logs. Can't figure it out.

Minecraft Bedrock Server Docker script by James A. Chambers
Latest version always at https://github.com/TheRemote/Legendary-Bedrock-Container
Don't forget to set up port forwarding on your router!  The default port is 19132
Ports used - IPV4: 19132 - IPV6: 19133
Taking ownership of all server files/folders in /minecraft...
Complete
Checking for the latest version of Minecraft Bedrock server ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  307k    0  307k    0     0   284k      0 --:--:--  0:00:01 --:--:--  284k
100  590k    0  590k    0     0   509k      0 --:--:--  0:00:01 --:--:--  509k
Latest version online is 
Latest version  is already installed
Starting Minecraft server...
/bin/bash: line 1: ./bedrock_server: No such file or directory

**Comment by GluteCramp** [comment]
I think it's failing to download the server files because the download link is different now (see the currently open pull request), so it's just failing and then exiting/repeating until it exits.

**Comment by TheRemote** [comment]
This is now fixed, thank you for reporting it!
