### ISSUE TITLE
I had some trouble to start 1.19.20.02

### ISSUE THREAD

**Issue by roelrens** [TheRemote/Legendary-Bedrock-Container#6]
I had a bump during this version.

if I gave a previous Version parameter in docker, all was allright , the startup worked without a charm
so my  issue is : 
the screen command which adds the timestamp 
 crashed bedrock server. 
 I disabled the whole if then else  if (resulting of removing the following part: in the actual screen command. 
 
`| gawk \'{ print strftime(\"[%Y-%m-%d %H:%M:%S]\"), $0 }\' `
here is a log file of that issue
[minecraft.2022.08.11.14.44.10.log](https://github.com/TheRemote/Legendary-Bedrock-Container/files/9310302/minecraft.2022.08.11.14.44.10.log).

Did you had no issues with 20.02 ? let me know. it could be a one-off. so do feel free to ignore me.

**Comment by TheRemote** [comment]
Wow how strange, thanks for including your log file!  It reminds me of this persons that was submitted recently:  https://jamesachambers.com/minecraft-bedrock-edition-ubuntu-dedicated-server-guide/#comment-14000

It's not exactly the same though.  You did both manage to enable a bunch of experimental flags.  I assume this means that you also imported a single player world that had some of the experimental boxes checked.  One thing I've never seen before in yours is that it says "Content Log enabled".  I've never seen this before and didn't think it was possible to really enable the Bedrock logging although I'm not surprised there is a way to do it.

I wonder though if this is causing a problem having the screen logging and the Bedrock logging (however it is enabled) turned on at the same time.  Like I said I have never seen this so it's possible and we've never really had anyone have trouble specifically with the screen command before so this is a really interesting case.

I'm fairly certain the server is corrupted in that person's case.  Yours I'm not so sure on.  You did some good testing trying the older version first.  In the past when this has happened it sometimes has meant that the dependencies changed and then I had to make some tweaks to get it to work again.  Are you using ARM or are you using amd64/x86_64?  If it's ARM then I probably need to fire up the Pis and do some testing.

**Comment by TheRemote** [comment]
Actually I'm seeing a bunch of dependency changes when I run ldd on bedrock_server.

Let me add these dependencies and update the container and we'll see if that takes care of it!

**Comment by roelrens** [comment]
Hi, 

I see that my setup updated yesterday. (forced it after my client got updated) 
I had another docker also running. and did my first upgrade by unzipping the file there. 
what iI forgot but have taken over from that setup is en environmental variable I now declare as well 
LD_LIBRARY_PATH=. 
it could be related. 

regarding the log output . 
there is a server.properties 
 parameter 
content-log-file-enabled=true
i probably changed that duriring one of the many reboots

**Comment by roelrens** [comment]
the content file logs are created next to the server (but only during the crashes) and contain no data.

**Comment by TheRemote** [comment]
I just added a new feature to help with this.  It's an environment variable called "Clean".  To use it you would add:

`-e Clean=Y`

to your Docker launch line.  You'd only have to do this once as it will clear out the downloads folder and version_installed.txt.  This will basically do what I was talking about earlier but makes it much more easy / convenient to use as this kind of thing can definitely happen when sharing volumes / multiple servers / many other reasons.

**Comment by roelrens** [comment]
I updated with the Clean=Y and it worked for me.

**Comment by TheRemote** [comment]
Hey roelrens,

Thanks for the followup!  I had closed this figured you were off to greener pastures but I'm glad you let me know this.  Enjoy and take care!
