### ISSUE TITLE
How to migrate server-data from stand alone to bedrock container

### ISSUE THREAD

**Issue by KimTholstorf** [TheRemote/Legendary-Bedrock-Container#9]
Is is possible to migrate the data from your standalone bedrock solution to this bedrock container?

Have had the standalone running for a really long time and do not want to destroy the world my kids have build in the existing standalone bedrock server

**Comment by TheRemote** [comment]
Hello,

Absolutely!  You can access the Docker volume filesystem and just copy paste them over into it believe it or not.  All the files are completely the same and there's nothing special/strange going on to make them incompatible.

These are typically located at:

[/var/lib/docker/volumes/yourvolumename](url)

There are some additional instructions in the README for if you are running a different platform.  You will basically just move the files from your server into there.

It would look something like:

`sudo cp /home/youruser/minecraftbe/yourserver /var/lib/docker/volumes/yourvolumename/_data`

Hopefully that helps!

**Comment by KimTholstorf** [comment]
indeed:-) Thank you!

**Comment by TheRemote** [comment]
You're welcome, enjoy and take care!

**Comment by cenobitedk** [comment]
This guide should be in the readme :)

**Comment by TheRemote** [comment]
It should be honestly.  I'm not happy with where the documentation is at.  It's definitely scheduled for a rework before too long and I will definitely make sure this makes it into the updated documentation.

Like the current documentation doesn't even teach people how to give it a container name with --name so there's a few other things I'm not happy with as well.  Thanks for leaving this as I don't know if I would have remembered this specific one for the rework.  Thanks!

**Comment by StormBringer228** [comment]
The directory leads gives me a folder with 3 items. A data folder with Docker.raw inside, a log folder with nothing in it and a macaddr-0 document. Where do i put the contents of the unpacked .mcworld file
